/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IViewModule,
  IViewModuleInterface,
} from "../../../../../contracts/interfaces/modules/base/IViewModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "ipAccount",
        type: "address",
      },
    ],
    name: "isSupported",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IViewModule__factory {
  static readonly abi = _abi;
  static createInterface(): IViewModuleInterface {
    return new Interface(_abi) as IViewModuleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IViewModule {
    return new Contract(address, _abi, runner) as unknown as IViewModule;
  }
}
