/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as storyNftFactorySol from "./StoryNFTFactory.sol";
export type { storyNftFactorySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as lib from "./lib";
export type { lib };
export type { StoryNFT } from "./StoryNFT";
