/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uma from "./UMA";
export type { uma };
export type { IArbitrationPolicy } from "./IArbitrationPolicy";
