/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IExternalRoyaltyPolicy } from "./IExternalRoyaltyPolicy";
export type { IExternalRoyaltyPolicyBase } from "./IExternalRoyaltyPolicyBase";
export type { IGraphAwareRoyaltyPolicy } from "./IGraphAwareRoyaltyPolicy";
export type { IIpRoyaltyVault } from "./IIpRoyaltyVault";
export type { IRoyaltyPolicy } from "./IRoyaltyPolicy";
export type { IVaultController } from "./IVaultController";
