/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IRoyaltyPolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPolicyRoyaltyStack"
      | "getPolicyRtsRequiredToLink"
      | "isSupportGroup"
      | "onLicenseMinting"
      | "onLinkToParents"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPolicyRoyaltyStack",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicyRtsRequiredToLink",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupportGroup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onLicenseMinting",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onLinkToParents",
    values: [
      AddressLike,
      AddressLike[],
      AddressLike[],
      BigNumberish[],
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPolicyRoyaltyStack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPolicyRtsRequiredToLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSupportGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onLicenseMinting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onLinkToParents",
    data: BytesLike
  ): Result;
}

export interface IRoyaltyPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): IRoyaltyPolicy;
  waitForDeployment(): Promise<this>;

  interface: IRoyaltyPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPolicyRoyaltyStack: TypedContractMethod<
    [ipId: AddressLike],
    [bigint],
    "view"
  >;

  getPolicyRtsRequiredToLink: TypedContractMethod<
    [ipId: AddressLike, licensePercent: BigNumberish],
    [bigint],
    "view"
  >;

  isSupportGroup: TypedContractMethod<[], [boolean], "view">;

  onLicenseMinting: TypedContractMethod<
    [ipId: AddressLike, licensePercent: BigNumberish, externalData: BytesLike],
    [void],
    "nonpayable"
  >;

  onLinkToParents: TypedContractMethod<
    [
      ipId: AddressLike,
      parentIpIds: AddressLike[],
      licenseRoyaltyPolicies: AddressLike[],
      licensesPercent: BigNumberish[],
      externalData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPolicyRoyaltyStack"
  ): TypedContractMethod<[ipId: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPolicyRtsRequiredToLink"
  ): TypedContractMethod<
    [ipId: AddressLike, licensePercent: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSupportGroup"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "onLicenseMinting"
  ): TypedContractMethod<
    [ipId: AddressLike, licensePercent: BigNumberish, externalData: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onLinkToParents"
  ): TypedContractMethod<
    [
      ipId: AddressLike,
      parentIpIds: AddressLike[],
      licenseRoyaltyPolicies: AddressLike[],
      licensesPercent: BigNumberish[],
      externalData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
