/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IVaultControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ipRoyaltyVaultBeacon"
      | "setIpRoyaltyVaultBeacon"
      | "upgradeVaults"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ipRoyaltyVaultBeacon",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setIpRoyaltyVaultBeacon",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeVaults",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ipRoyaltyVaultBeacon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIpRoyaltyVaultBeacon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeVaults",
    data: BytesLike
  ): Result;
}

export interface IVaultController extends BaseContract {
  connect(runner?: ContractRunner | null): IVaultController;
  waitForDeployment(): Promise<this>;

  interface: IVaultControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ipRoyaltyVaultBeacon: TypedContractMethod<[], [string], "view">;

  setIpRoyaltyVaultBeacon: TypedContractMethod<
    [beacon: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeVaults: TypedContractMethod<
    [newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ipRoyaltyVaultBeacon"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setIpRoyaltyVaultBeacon"
  ): TypedContractMethod<[beacon: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeVaults"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;

  filters: {};
}
