/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ILicensingHookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beforeMintLicenseTokens"
      | "beforeRegisterDerivative"
      | "calculateMintingFee"
      | "name"
      | "supportsInterface"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "beforeMintLicenseTokens",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeRegisterDerivative",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateMintingFee",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "beforeMintLicenseTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeRegisterDerivative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateMintingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export interface ILicensingHook extends BaseContract {
  connect(runner?: ContractRunner | null): ILicensingHook;
  waitForDeployment(): Promise<this>;

  interface: ILicensingHookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beforeMintLicenseTokens: TypedContractMethod<
    [
      caller: AddressLike,
      licensorIpId: AddressLike,
      licenseTemplate: AddressLike,
      licenseTermsId: BigNumberish,
      amount: BigNumberish,
      receiver: AddressLike,
      hookData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  beforeRegisterDerivative: TypedContractMethod<
    [
      caller: AddressLike,
      childIpId: AddressLike,
      parentIpId: AddressLike,
      licenseTemplate: AddressLike,
      licenseTermsId: BigNumberish,
      hookData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  calculateMintingFee: TypedContractMethod<
    [
      caller: AddressLike,
      licensorIpId: AddressLike,
      licenseTemplate: AddressLike,
      licenseTermsId: BigNumberish,
      amount: BigNumberish,
      receiver: AddressLike,
      hookData: BytesLike
    ],
    [bigint],
    "view"
  >;

  name: TypedContractMethod<[], [string], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beforeMintLicenseTokens"
  ): TypedContractMethod<
    [
      caller: AddressLike,
      licensorIpId: AddressLike,
      licenseTemplate: AddressLike,
      licenseTermsId: BigNumberish,
      amount: BigNumberish,
      receiver: AddressLike,
      hookData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeRegisterDerivative"
  ): TypedContractMethod<
    [
      caller: AddressLike,
      childIpId: AddressLike,
      parentIpId: AddressLike,
      licenseTemplate: AddressLike,
      licenseTermsId: BigNumberish,
      hookData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateMintingFee"
  ): TypedContractMethod<
    [
      caller: AddressLike,
      licensorIpId: AddressLike,
      licenseTemplate: AddressLike,
      licenseTermsId: BigNumberish,
      amount: BigNumberish,
      receiver: AddressLike,
      hookData: BytesLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  filters: {};
}
