/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILicenseTemplate } from "./ILicenseTemplate";
export type { ILicensingHook } from "./ILicensingHook";
export type { ILicensingModule } from "./ILicensingModule";
export type { IPILicenseTemplate } from "./IPILicenseTemplate";
