/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./access";
export type { access };
import type * as modules from "./modules";
export type { modules };
import type * as pause from "./pause";
export type { pause };
import type * as registries from "./registries";
export type { registries };
export type { IGroupNFT } from "./IGroupNFT";
export type { IIPAccount } from "./IIPAccount";
export type { IIPAccountStorage } from "./IIPAccountStorage";
export type { ILicenseToken } from "./ILicenseToken";
