/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export declare namespace IOOV3 {
  export type EscalationManagerSettingsStruct = {
    arbitrateViaEscalationManager: boolean;
    discardOracle: boolean;
    validateDisputers: boolean;
    assertingCaller: AddressLike;
    escalationManager: AddressLike;
  };

  export type EscalationManagerSettingsStructOutput = [
    arbitrateViaEscalationManager: boolean,
    discardOracle: boolean,
    validateDisputers: boolean,
    assertingCaller: string,
    escalationManager: string
  ] & {
    arbitrateViaEscalationManager: boolean;
    discardOracle: boolean;
    validateDisputers: boolean;
    assertingCaller: string;
    escalationManager: string;
  };

  export type AssertionStruct = {
    escalationManagerSettings: IOOV3.EscalationManagerSettingsStruct;
    asserter: AddressLike;
    assertionTime: BigNumberish;
    settled: boolean;
    currency: AddressLike;
    expirationTime: BigNumberish;
    settlementResolution: boolean;
    domainId: BytesLike;
    identifier: BytesLike;
    bond: BigNumberish;
    callbackRecipient: AddressLike;
    disputer: AddressLike;
  };

  export type AssertionStructOutput = [
    escalationManagerSettings: IOOV3.EscalationManagerSettingsStructOutput,
    asserter: string,
    assertionTime: bigint,
    settled: boolean,
    currency: string,
    expirationTime: bigint,
    settlementResolution: boolean,
    domainId: string,
    identifier: string,
    bond: bigint,
    callbackRecipient: string,
    disputer: string
  ] & {
    escalationManagerSettings: IOOV3.EscalationManagerSettingsStructOutput;
    asserter: string;
    assertionTime: bigint;
    settled: boolean;
    currency: string;
    expirationTime: bigint;
    settlementResolution: boolean;
    domainId: string;
    identifier: string;
    bond: bigint;
    callbackRecipient: string;
    disputer: string;
  };
}

export interface IOOV3Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "assertTruth"
      | "burnedBondPercentage"
      | "disputeAssertion"
      | "getAssertion"
      | "getMinimumBond"
      | "settleAssertion"
      | "stampAssertion"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assertTruth",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "burnedBondPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeAssertion",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssertion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumBond",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAssertion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stampAssertion",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "assertTruth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnedBondPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeAssertion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssertion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAssertion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stampAssertion",
    data: BytesLike
  ): Result;
}

export interface IOOV3 extends BaseContract {
  connect(runner?: ContractRunner | null): IOOV3;
  waitForDeployment(): Promise<this>;

  interface: IOOV3Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assertTruth: TypedContractMethod<
    [
      claim: BytesLike,
      asserter: AddressLike,
      callbackRecipient: AddressLike,
      escalationManager: AddressLike,
      liveness: BigNumberish,
      currency: AddressLike,
      bond: BigNumberish,
      identifier: BytesLike,
      domainId: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  burnedBondPercentage: TypedContractMethod<[], [bigint], "view">;

  disputeAssertion: TypedContractMethod<
    [assertionId: BytesLike, disputer: AddressLike],
    [void],
    "nonpayable"
  >;

  getAssertion: TypedContractMethod<
    [assertionId: BytesLike],
    [IOOV3.AssertionStructOutput],
    "view"
  >;

  getMinimumBond: TypedContractMethod<
    [currency: AddressLike],
    [bigint],
    "view"
  >;

  settleAssertion: TypedContractMethod<
    [assertionId: BytesLike],
    [void],
    "nonpayable"
  >;

  stampAssertion: TypedContractMethod<
    [assertionId: BytesLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assertTruth"
  ): TypedContractMethod<
    [
      claim: BytesLike,
      asserter: AddressLike,
      callbackRecipient: AddressLike,
      escalationManager: AddressLike,
      liveness: BigNumberish,
      currency: AddressLike,
      bond: BigNumberish,
      identifier: BytesLike,
      domainId: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burnedBondPercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeAssertion"
  ): TypedContractMethod<
    [assertionId: BytesLike, disputer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAssertion"
  ): TypedContractMethod<
    [assertionId: BytesLike],
    [IOOV3.AssertionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMinimumBond"
  ): TypedContractMethod<[currency: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "settleAssertion"
  ): TypedContractMethod<[assertionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stampAssertion"
  ): TypedContractMethod<[assertionId: BytesLike], [string], "view">;

  filters: {};
}
