/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGraphAwareRoyaltyPolicy,
  IGraphAwareRoyaltyPolicyInterface,
} from "../../../../../../contracts/interfaces/modules/royalty/policies/IGraphAwareRoyaltyPolicy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "ancestorIpId",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "RevenueTransferredToVault",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "address",
        name: "ancestorIpId",
        type: "address",
      },
    ],
    name: "getPolicyRoyalty",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
    ],
    name: "getPolicyRoyaltyStack",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "licensePercent",
        type: "uint32",
      },
    ],
    name: "getPolicyRtsRequiredToLink",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "address",
        name: "ancestorIpId",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getTransferredTokens",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isSupportGroup",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "licensePercent",
        type: "uint32",
      },
      {
        internalType: "bytes",
        name: "externalData",
        type: "bytes",
      },
    ],
    name: "onLicenseMinting",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "parentIpIds",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "licenseRoyaltyPolicies",
        type: "address[]",
      },
      {
        internalType: "uint32[]",
        name: "licensesPercent",
        type: "uint32[]",
      },
      {
        internalType: "bytes",
        name: "externalData",
        type: "bytes",
      },
    ],
    name: "onLinkToParents",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "address",
        name: "ancestorIpId",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "transferToVault",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGraphAwareRoyaltyPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IGraphAwareRoyaltyPolicyInterface {
    return new Interface(_abi) as IGraphAwareRoyaltyPolicyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGraphAwareRoyaltyPolicy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IGraphAwareRoyaltyPolicy;
  }
}
