/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IExternalRoyaltyPolicy__factory } from "./IExternalRoyaltyPolicy__factory";
export { IExternalRoyaltyPolicyBase__factory } from "./IExternalRoyaltyPolicyBase__factory";
export { IGraphAwareRoyaltyPolicy__factory } from "./IGraphAwareRoyaltyPolicy__factory";
export { IIpRoyaltyVault__factory } from "./IIpRoyaltyVault__factory";
export { IRoyaltyPolicy__factory } from "./IRoyaltyPolicy__factory";
export { IVaultController__factory } from "./IVaultController__factory";
