/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRoyaltyPolicy,
  IRoyaltyPolicyInterface,
} from "../../../../../../contracts/interfaces/modules/royalty/policies/IRoyaltyPolicy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
    ],
    name: "getPolicyRoyaltyStack",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "licensePercent",
        type: "uint32",
      },
    ],
    name: "getPolicyRtsRequiredToLink",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isSupportGroup",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "licensePercent",
        type: "uint32",
      },
      {
        internalType: "bytes",
        name: "externalData",
        type: "bytes",
      },
    ],
    name: "onLicenseMinting",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "parentIpIds",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "licenseRoyaltyPolicies",
        type: "address[]",
      },
      {
        internalType: "uint32[]",
        name: "licensesPercent",
        type: "uint32[]",
      },
      {
        internalType: "bytes",
        name: "externalData",
        type: "bytes",
      },
    ],
    name: "onLinkToParents",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRoyaltyPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IRoyaltyPolicyInterface {
    return new Interface(_abi) as IRoyaltyPolicyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRoyaltyPolicy {
    return new Contract(address, _abi, runner) as unknown as IRoyaltyPolicy;
  }
}
