/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IHookModule } from "./IHookModule";
export type { IModule } from "./IModule";
export type { IViewModule } from "./IViewModule";
