/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
import type * as dispute from "./dispute";
export type { dispute };
import type * as grouping from "./grouping";
export type { grouping };
import type * as licensing from "./licensing";
export type { licensing };
import type * as metadata from "./metadata";
export type { metadata };
import type * as royalty from "./royalty";
export type { royalty };
