/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICoreMetadataModule } from "./ICoreMetadataModule";
export type { ICoreMetadataViewModule } from "./ICoreMetadataViewModule";
