/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILicenseTemplate__factory } from "./ILicenseTemplate__factory";
export { ILicensingHook__factory } from "./ILicensingHook__factory";
export { ILicensingModule__factory } from "./ILicensingModule__factory";
export { IPILicenseTemplate__factory } from "./IPILicenseTemplate__factory";
