/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGroupRewardPool } from "./IGroupRewardPool";
export type { IGroupingModule } from "./IGroupingModule";
